### ISSUE TITLE
Warning since HA Update to 2024.5

### ISSUE THREAD

**Issue by anym001** [dummylabs/thewatchman#131] opened 2024-05-07 06:11 UTC
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
Occurred for the first time: 07:58:32 (1 occurrences)
Last logged: 07:58:32

`HomeAssistantType was used from watchman, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'watchman' custom integration`

**Comment by cremor** [comment] 2024-05-12 08:07
Duplicate of #127

**Comment by dummylabs** [comment] 2024-06-21 13:25
Should be fixed in 0.6.2 along with #127

**Closed by dummylabs** 2024-06-21 13:25 UTC
