### ISSUE TITLE
Recorder warning: The unit of sensor.watchman_missing_entities is changing, got multiple

### ISSUE THREAD

**Issue by dummylabs** [dummylabs/thewatchman#86] opened 2023-03-02 09:10 UTC
```
Warning: The unit of sensor.watchman_missing_entities is changing, got multiple (None, 'items'), generation of long term statistics will be suspended unless the unit is stable and matches the unit of already compiled entities (Items).
```

**Comment by Calzor-Suzay** [comment] 2023-03-27 23:31
I think this is the same as #87 https://github.com/dummylabs/thewatchman/issues/87 but I have the same issue.
Not noticed it in the past.

Is Watchman the problem or did HA pull something that's made our missing entities explode...

**Comment by chemelli74** [comment] 2023-07-11 15:55
> I think this is the same as #87 #87 but I have the same issue. Not noticed it in the past.

Part is a duplicate of #87, part is not.

I suggest to rename the issue to something like "Warning caused by non-stable unit {None, 'items'}" to address the other warning.

My log on 2023.7.1:

`2023-07-11 17:50:10.265 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.watchman_missing_entities is changing, got multiple {None, 'items'}, generation of long term statistics will be suppressed unless the unit is stable and matches the unit of already compiled statistics (items). Go to https://my.home-assistant.io/redirect/developer_statistics to fix this`

Simone

**Closed** 2024-11-20 06:52 UTC
